//This file is automatically generated. DO NOT EDIT!
using System;
using RobotRaconteurWeb;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 0108

namespace experimental.create2
{
[RobotRaconteurServiceStruct("experimental.create2.SensorPacket")]
public class SensorPacket
{
    public byte ID;
    public byte[] Data;
}

[RobotRaconteurServiceObjectInterface("experimental.create2.Create")]
public interface Create
{
    Task<int> get_DistanceTraveled(CancellationToken cancel=default(CancellationToken));
    Task set_DistanceTraveled(int value, CancellationToken cancel=default(CancellationToken));
    Task<int> get_AngleTraveled(CancellationToken cancel=default(CancellationToken));
    Task set_AngleTraveled(int value, CancellationToken cancel=default(CancellationToken));
    Task<byte> get_Bumpers(CancellationToken cancel=default(CancellationToken));
    Task set_Bumpers(byte value, CancellationToken cancel=default(CancellationToken));
    Task Drive(short velocity, short radius,CancellationToken rr_cancel=default(CancellationToken));
    Task StartStreaming(CancellationToken rr_cancel=default(CancellationToken));
    Task StopStreaming(CancellationToken rr_cancel=default(CancellationToken));
    event Action Bump;
    Callback<Func<int, int, CancellationToken, Task<byte[]>>> play_callback {get; set;}
    Wire<SensorPacket> packets { get; set; }
}

public static class experimental__create2Constants  {
    public static class Create
    {
    public const short DRIVE_STRAIGHT=32767;
    public const short SPIN_CLOCKWISE=-1;
    public const short SPIN_COUNTERCLOCKWISE=1;
    }
}
}
